### ISSUE TITLE
License

### ISSUE THREAD

**Issue by icyield** [fhydralisk/apnsprovider#1]
Hi .  What is the license for reuse as part of another project?

**Comment by fhydralisk** [comment]
Hi, there.
You are free to copy, reuse or modify the source as you wish.
I've considered to add a BSD2 LICENSE.

**Comment by icyield** [comment]
BSD2 or MIT are good. If there is no licence then people cannot use in other projects. Thanks.

**Comment by fhydralisk** [comment]
Thanks, BSD2 License added.
